language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - whoami
  - pwd
  - ls
  - git status
  - ls ~
  - echo $HOME
  - env
  - git clone https://github.com/torch/distro.git ~/torch --recursive
  - cd ~/torch
  - for pkg in cudnn cunn cunnx cutorch qttorch optim sdl2 threads graphicsmagick audio fftw3 signal nnx qtlua gnuplot dok iTorch argcheck image xlua; do { sed -i -e "s/\(.*$pkg.*\)/# \1/" install.sh; } done
  - ./install.sh
  - mkdir ~/git
  - cd ~/git
  - cd ~/build/hughperkins/cltorch

script:
  - echo hello
  - source ~/torch/install/bin/torch-activate
  - env
  - mkdir build
  - cd build
  - cmake ..
  - make -j 4

notifications:
  email:
    on_success: never
    on_failure: never

