language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - whoami
  - pwd
  - bash src/travis/install-torch.sh
  - source ~/torch/install/bin/torch-activate
  - luajit -l torch -e 'print(torch.Tensor(3,2):uniform())'
  - mkdir ~/git
  - cd ~/git
  - cd ~/build/hughperkins/cltorch

script:
  - cat ~/torch/install/bin/torch-activate
  - source ~/torch/install/bin/torch-activate
  - luarocks make rocks/cltorch-scm-1.rockspec
  - otool -L ~/torch/install/lib/lua/5.1/libcltorch.so
  - otool -l ~/torch/install/lib/lua/5.1/libcltorch.so | grep RPATH -A2
  - luajit -e 'require "cltorch"'
  - luajit -l cltorch -e "cltorch.setAllowNonGpus(1); print(cltorch.getDeviceCount())"
  - 'luajit -e "require ''cltorch''; cltorch.setAllowNonGpus(1); print(cltorch.getDeviceCount())"'
  - luajit -l cltorch -e "cltorch.setAllowNonGpus(1); props = cltorch.getDeviceProperties(1); for k,v in pairs(props) do print(k,v) end"
  - export TEST_EXCLUDES=test_blas,test_cumprod,test_cumsum,test_equals,test_indexcopy,test_indexfill,test_matrixwide,test_max2,test_mean,test_meanall,test_min2,test_norm,test_prod,test_prodall,test_sum_t,test_sumallt,test_reduceAll,test_sum,test_sum_t_offset,test_sumall
  - 'luajit -l cltorch -e "cltorch.setAllowNonGpus(1); cltorch.test()"'
  - zsh src/test/test-zsh.zsh
  - #zsh
  - #ps
  - #source ~/torch/install/bin/torch-activate
  - #luajit -e 'require "cltorch"'
  - #luajit -l cltorch -e "cltorch.setAllowNonGpus(1); print(cltorch.getDeviceCount())"
  - #'luajit -e "require ''cltorch''; cltorch.setAllowNonGpus(1); print(cltorch.getDeviceCount())"'
  - #luajit -l cltorch -e "cltorch.setAllowNonGpus(1); props = cltorch.getDeviceProperties(1); for k,v in pairs(props) do print(k,v) end"
  - #export TEST_EXCLUDES=test_blas,test_cumprod,test_cumsum,test_equals,test_indexcopy,test_indexfill,test_matrixwide,test_max2,test_mean,test_meanall,test_min2,test_norm,test_prod,test_prodall,test_sum_t,test_sumallt,test_reduceAll,test_sum,test_sum_t_offset,test_sumall

notifications:
  email:
    on_success: never
    on_failure: never

